// <auto-generated />
namespace ProvaHBSis.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class script_Inicial_ProvaHBSis_SQL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(script_Inicial_ProvaHBSis_SQL));
        
        string IMigrationMetadata.Id
        {
            get { return "201709281851438_script_Inicial_ProvaHBSis_SQL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
